-- Intentionally empty.
--
-- The application connects to MySQL as root, using MYSQL_ROOT_PASSWORD
-- (see docker-compose.yml, sourced from DB_PASSWORD in .env). No separate
-- application-level database user (e.g. the previously-defined `paruser`)
-- is actually used by par-backend or par-ml — both connect as root — so
-- this file no longer creates one.
--
-- Previously this file hardcoded a plaintext password for an unused
-- `paruser` account directly in committed source (see docs/BugLog.md,
-- BUG-005). That account and its bind-mount into
-- docker-entrypoint-initdb.d have been removed.
--
-- Schema/table DDL is owned entirely by Flyway migrations under
-- code/backend/src/main/resources/db/migration/ — nothing belongs in
-- this file unless it is genuinely outside Flyway's scope (e.g. one-time
-- server-level MySQL configuration that isn't a schema change).